### PR TITLE
Add ability to split multiple names/emails by comma or semicolon.

### PR DESCRIPTION
**Pull request by anehx**
This adds the ability to split multiple names or email addresses by comma or semicolon. It's is useful because many email clients split them by semicolon and you can copy and paste the email addresses better.

### CODE REVIEW

**Comment by lesterchan** [comment]
Sorry why are we removing the var? That will make the variable global scope.

**Comment by anehx** [comment]
Took a wrong file.. Fixed it by now

**Comment by lesterchan** [comment]
Can you rebase and send the pull request again? I can't merge it automatically.

**Comment by anehx** [comment]
Should work now.

**Pull request merged**
